### ISSUE TITLE
package error with scalatest

### ISSUE THREAD

**Issue by sarunkums** [cloudera-labs/SparkOnHBase#14]
hi, i'm attempting to use scalatest with Spark on Hbase, but receiving errors when attempting to package my code with sbt.  Following is my setup:

spark version: 1.6.1
hbase version 1.0.0-cdh5.5.0 (have also done this with 1.2.0-cdh5.7.0)
hadoop version 2.6.0-cdh5.7.0

scalatest 2.2.6
scala version: 2.11.7
spark-hbase 0.0.2-clabs

Errors I receive are as follows:

java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
  at org.scalatest.ConfigMap<init> (ConfigMap.scala:97)
 ...

When I remove Spark on Hbase from build.sbt, everything compiles, assembles, and packages correctly.  Any help on this would be appreciated.

**Comment by busbey** [comment]
The Spark On HBase project in Cloudera Labs got merged into the upstream HBase project in 2015 and a backport of that has shipped with CDH since CDH 5.7

https://blog.cloudera.com/blog/2015/08/apache-spark-comes-to-apache-hbase-with-hbase-spark-module/
