### ISSUE TITLE
2018 -- Support

### ISSUE THREAD

**Issue by Nico-Rode** [cloudera-labs/SparkOnHBase#17]
Hello! I take it this repo isn't maintained any longer? What would be the best way to use this project for querying an HBase instance from within spark?

Thanks,

**Comment by busbey** [comment]
The Spark On HBase project in Cloudera Labs got merged into the upstream HBase project in 2015 and a backport of that has shipped with CDH since CDH 5.7

https://blog.cloudera.com/blog/2015/08/apache-spark-comes-to-apache-hbase-with-hbase-spark-module/
